// automatically generated by spin2cpp v3.9.21 on Mon Mar  4 19:14:04 2019
// command line: spin2cpp --p2 --ccode vgatext_1024x768.spin2 

#ifndef vga_tile_driver_Class_Defined__
#define vga_tile_driver_Class_Defined__

#include <stdint.h>

//   basepin = 48
//   vsync = basepin + 4 ' vsync pin
// 0..128
#define VGA_TILE_DRIVER_INTENSITY (80)
#define VGA_TILE_DRIVER_PIXSHIFT (31)

typedef struct vga_tile_driver {
  int32_t 	mycog;
} vga_tile_driver;

  int32_t vga_tile_driver_start(vga_tile_driver *self, int32_t params);
  void vga_tile_driver_stop(vga_tile_driver *self);
  int32_t vga_tile_driver_calcscale(int32_t a, int32_t b);
#endif
