// automatically generated by spin2cpp v3.9.21 on Mon Mar  4 19:14:04 2019
// command line: spin2cpp --p2 --ccode vgatext_1024x768.spin2 

#ifndef vgatext_1024x768_Class_Defined__
#define vgatext_1024x768_Class_Defined__

#include <stdint.h>
#include "vga_tile_driver.h"

#define VGATEXT_1024X768_PIXEL_CLOCK_FREQ (65000000)
#define VGATEXT_1024X768_COLS (128)
#define VGATEXT_1024X768_ROWS (48)
#define VGATEXT_1024X768_FONT_HEIGHT (16)
#define VGATEXT_1024X768_STATE_NORMAL (0)
#define VGATEXT_1024X768_STATE_ESCAPE (1)
#define VGATEXT_1024X768_STATE_CSI (2)
#define VGATEXT_1024X768_MAX_ESC_ARGS (8)
#define VGATEXT_1024X768_CHAR_INVERSE (1)
#define VGATEXT_1024X768_CHAR_BOLD (2)
#define VGATEXT_1024X768_DEFAULT_FG_COLOR (-256)
#define VGATEXT_1024X768_DEFAULT_BG_COLOR (0)
#define VGATEXT_1024X768_PIXSHIFT (31)
#ifndef Tuple2__
  struct tuple2__ { int32_t v0;  int32_t v1; };
# define Tuple2__ struct tuple2__
#endif


typedef struct vgatext_1024x768 {
// parameters for running the VGA tile driver
  volatile int32_t 	params[40];
  volatile int32_t 	screen_buffer[((2 * VGATEXT_1024X768_ROWS) * VGATEXT_1024X768_COLS)];
  vga_tile_driver 	vga;
// cursor position
  int32_t 	curx, cury;
  int32_t 	savex, savey;
// current color
  int32_t 	bgcolor, fgcolor;
  int32_t 	state;
  int32_t 	screenptr;
  int32_t 	args[VGATEXT_1024X768_MAX_ESC_ARGS];
  int32_t 	argidx;
  int32_t 	char_effects;
  char 	buf[32];
} vgatext_1024x768;

  int32_t vgatext_1024x768_start(vgatext_1024x768 *self, int32_t pinbase);
  void vgatext_1024x768_stop(vgatext_1024x768 *self);
  void vgatext_1024x768_tx(vgatext_1024x768 *self, int32_t c);
  void vgatext_1024x768_glyphat(vgatext_1024x768 *self, int32_t x, int32_t y, int32_t ch, int32_t fgcol, int32_t bgcol);
  void vgatext_1024x768_cls(vgatext_1024x768 *self);
  void vgatext_1024x768_str(vgatext_1024x768 *self, const char *s);
  void vgatext_1024x768_num(vgatext_1024x768 *self, int32_t val, int32_t base, int32_t signflag, int32_t digitsneeded);
  void vgatext_1024x768_dec(vgatext_1024x768 *self, int32_t val);
  void vgatext_1024x768_decuns(vgatext_1024x768 *self, int32_t val, int32_t digits);
  void vgatext_1024x768_hex(vgatext_1024x768 *self, int32_t val, int32_t digits);
  void vgatext_1024x768_nl(vgatext_1024x768 *self);
#endif
